import { Document, Packer, Paragraph, Table, TableRow, TableCell, TextRun, WidthType, HeadingLevel } from 'docx';

interface RiskEvent {
  riskId: string;
  title: string;
  level: string;
  category: string;
  owner: string;
  assessor: string;
  inherentRisk: string;
  inherentTrend: string;
  controls: string;
  effectiveness: string;
  testResults: string;
  residualRisk: string;
  residualTrend: string;
  status: string;
  lastAssessed: string;
}

const riskData: RiskEvent[] = [
  { riskId: "R-001", title: "Process Failure - Event 1", level: "Level 3", category: "Operational", owner: "Mike Davis", assessor: "External Auditor", inherentRisk: "[35, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-002: Process Failure Control", effectiveness: "Ineffective", testResults: "Pending", residualRisk: "[35, Medium]", residualTrend: "↓Decreasing", status: "Sent for Assessment", lastAssessed: "12/12/2025" },
  { riskId: "R-002", title: "Process Failure - Event 2", level: "Level 3", category: "Operational", owner: "Lisa Martinez", assessor: "Compliance Team", inherentRisk: "[35, Medium]", inherentTrend: "→Stable", controls: "CTRL-003: Process Failure Control", effectiveness: "Partially Effective", testResults: "Fail", residualRisk: "[35, Medium]", residualTrend: "↓Decreasing", status: "Pending Approval", lastAssessed: "12/21/2025" },
  { riskId: "R-003", title: "Process Failure - Event 3", level: "Level 3", category: "Operational", owner: "Alex Turner", assessor: "Compliance Team", inherentRisk: "[48, High]", inherentTrend: "→Stable", controls: "CTRL-004: Process Failure Control", effectiveness: "Ineffective", testResults: "Pending", residualRisk: "[35, Medium]", residualTrend: "↑Increasing", status: "Sent for Assessment", lastAssessed: "01/12/2026" },
  { riskId: "R-004", title: "Process Failure - Event 4", level: "Level 2", category: "Operational", owner: "Maria Garcia", assessor: "External Auditor", inherentRisk: "[18, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-005: Process Failure Control", effectiveness: "Partially Effective", testResults: "Not Tested", residualRisk: "[8, Low]", residualTrend: "↓Decreasing", status: "Pending Approval", lastAssessed: "12/08/2025" },
  { riskId: "R-005", title: "Process Failure - Event 5", level: "Level 3", category: "Operational", owner: "John Smith", assessor: "Internal Audit", inherentRisk: "[24, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-006: Process Failure Control", effectiveness: "Design Effective", testResults: "Pending", residualRisk: "[24, Medium]", residualTrend: "↓Decreasing", status: "Sent for Assessment", lastAssessed: "02/05/2026" },
  { riskId: "R-006", title: "Process Failure - Event 6", level: "Level 3", category: "Operational", owner: "Lisa Martinez", assessor: "External Auditor", inherentRisk: "[35, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-007: Process Failure Control", effectiveness: "Ineffective", testResults: "Pending", residualRisk: "[8, Low]", residualTrend: "↑Increasing", status: "Completed", lastAssessed: "12/20/2025" },
  { riskId: "R-007", title: "Process Failure - Event 7", level: "Level 3", category: "Operational", owner: "Mike Davis", assessor: "External Auditor", inherentRisk: "[24, Medium]", inherentTrend: "→Stable", controls: "CTRL-008: Process Failure Control", effectiveness: "Ineffective", testResults: "Fail", residualRisk: "[24, Medium]", residualTrend: "→Stable", status: "Pending Approval", lastAssessed: "12/21/2025" },
  { riskId: "R-008", title: "Human Error - Event 8", level: "Level 1", category: "Operational", owner: "Mike Davis", assessor: "Risk Team A", inherentRisk: "[18, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-009: Human Error Control", effectiveness: "Partially Effective", testResults: "Not Tested", residualRisk: "[18, Medium]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "01/23/2026" },
  { riskId: "R-009", title: "Human Error - Event 9", level: "Level 3", category: "Operational", owner: "David Wilson", assessor: "Compliance Team", inherentRisk: "[18, Medium]", inherentTrend: "→Stable", controls: "CTRL-010: Human Error Control", effectiveness: "Partially Effective", testResults: "Pending", residualRisk: "[8, Low]", residualTrend: "↓Decreasing", status: "Pending Approval", lastAssessed: "01/26/2026" },
  { riskId: "R-010", title: "Human Error - Event 10", level: "Level 2", category: "Operational", owner: "Lisa Martinez", assessor: "Compliance Team", inherentRisk: "[18, Medium]", inherentTrend: "→Stable", controls: "CTRL-011: Human Error Control", effectiveness: "Partially Effective", testResults: "Pass", residualRisk: "[18, Medium]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "12/08/2025" },
  { riskId: "R-011", title: "Human Error - Event 11", level: "Level 2", category: "Operational", owner: "John Smith", assessor: "External Auditor", inherentRisk: "[24, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-012: Human Error Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[35, Medium]", residualTrend: "→Stable", status: "Sent for Assessment", lastAssessed: "01/11/2026" },
  { riskId: "R-012", title: "Human Error - Event 12", level: "Level 2", category: "Operational", owner: "Emily Chen", assessor: "Internal Audit", inherentRisk: "[18, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-013: Human Error Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[8, Low]", residualTrend: "↑Increasing", status: "Sent for Assessment", lastAssessed: "12/08/2025" },
  { riskId: "R-013", title: "Human Error - Event 13", level: "Level 3", category: "Operational", owner: "Robert Chen", assessor: "Internal Audit", inherentRisk: "[24, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-014: Human Error Control", effectiveness: "Partially Effective", testResults: "Not Tested", residualRisk: "[24, Medium]", residualTrend: "↓Decreasing", status: "Sent for Assessment", lastAssessed: "01/19/2026" },
  { riskId: "R-014", title: "Human Error - Event 14", level: "Level 3", category: "Operational", owner: "Nina Patel", assessor: "Internal Audit", inherentRisk: "[18, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-015: Human Error Control", effectiveness: "Partially Effective", testResults: "Fail", residualRisk: "[24, Medium]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "12/08/2025" },
  { riskId: "R-015", title: "System Outage - Event 15", level: "Level 3", category: "Operational", owner: "John Smith", assessor: "Internal Audit", inherentRisk: "[18, Medium]", inherentTrend: "→Stable", controls: "CTRL-016: System Outage Control", effectiveness: "Ineffective", testResults: "Fail", residualRisk: "[18, Medium]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "12/30/2025" },
  { riskId: "R-016", title: "System Outage - Event 16", level: "Level 3", category: "Operational", owner: "Nina Patel", assessor: "Risk Team B", inherentRisk: "[35, Medium]", inherentTrend: "→Stable", controls: "CTRL-017: System Outage Control", effectiveness: "Partially Effective", testResults: "Pending", residualRisk: "[18, Medium]", residualTrend: "→Stable", status: "Sent for Assessment", lastAssessed: "12/19/2025" },
  { riskId: "R-017", title: "System Outage - Event 17", level: "Level 3", category: "Operational", owner: "Emily Chen", assessor: "Risk Team A", inherentRisk: "[24, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-018: System Outage Control", effectiveness: "Ineffective", testResults: "Not Tested", residualRisk: "[8, Low]", residualTrend: "→Stable", status: "Pending Approval", lastAssessed: "12/13/2025" },
  { riskId: "R-018", title: "System Outage - Event 18", level: "Level 1", category: "Operational", owner: "David Wilson", assessor: "External Auditor", inherentRisk: "[24, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-019: System Outage Control", effectiveness: "Partially Effective", testResults: "Not Tested", residualRisk: "[8, Low]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "12/15/2025" },
  { riskId: "R-019", title: "System Outage - Event 19", level: "Level 1", category: "Operational", owner: "Robert Chen", assessor: "External Auditor", inherentRisk: "[24, Medium]", inherentTrend: "→Stable", controls: "CTRL-020: System Outage Control", effectiveness: "Design Effective", testResults: "Not Tested", residualRisk: "[8, Low]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "01/31/2026" },
  { riskId: "R-020", title: "System Outage - Event 20", level: "Level 1", category: "Operational", owner: "Alex Turner", assessor: "Internal Audit", inherentRisk: "[24, Medium]", inherentTrend: "→Stable", controls: "CTRL-021: System Outage Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[24, Medium]", residualTrend: "↓Decreasing", status: "Sent for Assessment", lastAssessed: "01/19/2026" },
  { riskId: "R-021", title: "System Outage - Event 21", level: "Level 2", category: "Operational", owner: "John Smith", assessor: "External Auditor", inherentRisk: "[24, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-022: System Outage Control", effectiveness: "Ineffective", testResults: "Fail", residualRisk: "[8, Low]", residualTrend: "→Stable", status: "Completed", lastAssessed: "12/08/2025" },
  { riskId: "R-022", title: "Credit Risk - Event 22", level: "Level 2", category: "Financial", owner: "Lisa Martinez", assessor: "Risk Team A", inherentRisk: "[18, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-023: Credit Risk Control", effectiveness: "Design Effective", testResults: "Pending", residualRisk: "[35, Medium]", residualTrend: "→Stable", status: "Completed", lastAssessed: "12/13/2025" },
  { riskId: "R-023", title: "Credit Risk - Event 23", level: "Level 1", category: "Financial", owner: "Robert Chen", assessor: "Risk Team A", inherentRisk: "[24, Medium]", inherentTrend: "→Stable", controls: "CTRL-024: Credit Risk Control", effectiveness: "Partially Effective", testResults: "Pending", residualRisk: "[24, Medium]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "01/13/2026" },
  { riskId: "R-024", title: "Credit Risk - Event 24", level: "Level 2", category: "Financial", owner: "Lisa Martinez", assessor: "Risk Team A", inherentRisk: "[48, High]", inherentTrend: "↑Increasing", controls: "CTRL-025: Credit Risk Control", effectiveness: "Partially Effective", testResults: "Not Tested", residualRisk: "[18, Medium]", residualTrend: "↓Decreasing", status: "Completed", lastAssessed: "12/09/2025" },
  { riskId: "R-025", title: "Credit Risk - Event 25", level: "Level 2", category: "Financial", owner: "Emily Chen", assessor: "External Auditor", inherentRisk: "[35, Medium]", inherentTrend: "→Stable", controls: "CTRL-026: Credit Risk Control", effectiveness: "Design Effective", testResults: "Pending", residualRisk: "[8, Low]", residualTrend: "↑Increasing", status: "Sent for Assessment", lastAssessed: "12/08/2025" },
  { riskId: "R-026", title: "Credit Risk - Event 26", level: "Level 2", category: "Financial", owner: "Emily Chen", assessor: "Internal Audit", inherentRisk: "[56, High]", inherentTrend: "↑Increasing", controls: "CTRL-027: Credit Risk Control", effectiveness: "Ineffective", testResults: "Pass", residualRisk: "[24, Medium]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "12/23/2025" },
  { riskId: "R-027", title: "Credit Risk - Event 27", level: "Level 3", category: "Financial", owner: "Alex Turner", assessor: "Compliance Team", inherentRisk: "[24, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-028: Credit Risk Control", effectiveness: "Ineffective", testResults: "Fail", residualRisk: "[8, Low]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "12/26/2025" },
  { riskId: "R-028", title: "Credit Risk - Event 28", level: "Level 1", category: "Financial", owner: "David Wilson", assessor: "Internal Audit", inherentRisk: "[18, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-029: Credit Risk Control", effectiveness: "Partially Effective", testResults: "Fail", residualRisk: "[35, Medium]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "11/13/2025" },
  { riskId: "R-029", title: "Market Risk - Event 29", level: "Level 3", category: "Financial", owner: "Sarah Johnson", assessor: "External Auditor", inherentRisk: "[48, High]", inherentTrend: "→Stable", controls: "CTRL-030: Market Risk Control", effectiveness: "Ineffective", testResults: "Not Tested", residualRisk: "[18, Medium]", residualTrend: "↑Increasing", status: "Review & Challenge", lastAssessed: "12/22/2025" },
  { riskId: "R-030", title: "Market Risk - Event 30", level: "Level 3", category: "Financial", owner: "Sarah Johnson", assessor: "Risk Team A", inherentRisk: "[35, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-031: Market Risk Control", effectiveness: "Partially Effective", testResults: "Not Tested", residualRisk: "[35, Medium]", residualTrend: "→Stable", status: "Review & Challenge", lastAssessed: "02/04/2026" },
  { riskId: "R-031", title: "Market Risk - Event 31", level: "Level 2", category: "Financial", owner: "Maria Garcia", assessor: "External Auditor", inherentRisk: "[24, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-032: Market Risk Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[35, Medium]", residualTrend: "→Stable", status: "Completed", lastAssessed: "12/18/2025" },
  { riskId: "R-032", title: "Market Risk - Event 32", level: "Level 3", category: "Financial", owner: "David Wilson", assessor: "External Auditor", inherentRisk: "[48, High]", inherentTrend: "↓Decreasing", controls: "CTRL-033: Market Risk Control", effectiveness: "Partially Effective", testResults: "Pass", residualRisk: "[8, Low]", residualTrend: "↓Decreasing", status: "Completed", lastAssessed: "01/09/2026" },
  { riskId: "R-033", title: "Market Risk - Event 33", level: "Level 2", category: "Financial", owner: "Nina Patel", assessor: "Risk Team A", inherentRisk: "[24, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-034: Market Risk Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[18, Medium]", residualTrend: "↓Decreasing", status: "Sent for Assessment", lastAssessed: "12/08/2025" },
  { riskId: "R-034", title: "Market Risk - Event 34", level: "Level 2", category: "Financial", owner: "John Smith", assessor: "Risk Team A", inherentRisk: "[56, High]", inherentTrend: "↑Increasing", controls: "CTRL-035: Market Risk Control", effectiveness: "Ineffective", testResults: "Pending", residualRisk: "[24, Medium]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "12/23/2025" },
  { riskId: "R-035", title: "Market Risk - Event 35", level: "Level 3", category: "Financial", owner: "Emily Chen", assessor: "Compliance Team", inherentRisk: "[48, High]", inherentTrend: "↓Decreasing", controls: "CTRL-036: Market Risk Control", effectiveness: "Partially Effective", testResults: "Pass", residualRisk: "[18, Medium]", residualTrend: "→Stable", status: "Completed", lastAssessed: "01/21/2026" },
  { riskId: "R-036", title: "Liquidity Risk - Event 36", level: "Level 2", category: "Financial", owner: "Sarah Johnson", assessor: "Internal Audit", inherentRisk: "[24, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-037: Liquidity Risk Control", effectiveness: "Design Effective", testResults: "Not Tested", residualRisk: "[35, Medium]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "02/01/2026" },
  { riskId: "R-037", title: "Liquidity Risk - Event 37", level: "Level 3", category: "Financial", owner: "Mike Davis", assessor: "Internal Audit", inherentRisk: "[24, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-038: Liquidity Risk Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[8, Low]", residualTrend: "→Stable", status: "Pending Approval", lastAssessed: "01/24/2026" },
  { riskId: "R-038", title: "Liquidity Risk - Event 38", level: "Level 1", category: "Financial", owner: "Mike Davis", assessor: "External Auditor", inherentRisk: "[48, High]", inherentTrend: "↑Increasing", controls: "CTRL-039: Liquidity Risk Control", effectiveness: "Partially Effective", testResults: "Not Tested", residualRisk: "[24, Medium]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "12/08/2025" },
  { riskId: "R-039", title: "Liquidity Risk - Event 39", level: "Level 1", category: "Financial", owner: "Lisa Martinez", assessor: "Compliance Team", inherentRisk: "[18, Medium]", inherentTrend: "→Stable", controls: "CTRL-040: Liquidity Risk Control", effectiveness: "Design Effective", testResults: "Pending", residualRisk: "[8, Low]", residualTrend: "↑Increasing", status: "Completed", lastAssessed: "12/08/2025" },
  { riskId: "R-040", title: "Liquidity Risk - Event 40", level: "Level 2", category: "Financial", owner: "Mike Davis", assessor: "Internal Audit", inherentRisk: "[18, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-041: Liquidity Risk Control", effectiveness: "Design Effective", testResults: "Pending", residualRisk: "[24, Medium]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "01/28/2026" },
  { riskId: "R-041", title: "Liquidity Risk - Event 41", level: "Level 3", category: "Financial", owner: "Nina Patel", assessor: "Compliance Team", inherentRisk: "[18, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-042: Liquidity Risk Control", effectiveness: "Ineffective", testResults: "Not Tested", residualRisk: "[8, Low]", residualTrend: "→Stable", status: "Sent for Assessment", lastAssessed: "12/08/2025" },
  { riskId: "R-042", title: "Liquidity Risk - Event 42", level: "Level 2", category: "Financial", owner: "Robert Chen", assessor: "Internal Audit", inherentRisk: "[24, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-043: Liquidity Risk Control", effectiveness: "Ineffective", testResults: "Pass", residualRisk: "[18, Medium]", residualTrend: "→Stable", status: "Review & Challenge", lastAssessed: "01/03/2026" },
  { riskId: "R-043", title: "Regulatory Breach - Event 43", level: "Level 3", category: "Compliance", owner: "Mike Davis", assessor: "Risk Team A", inherentRisk: "[18, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-044: Regulatory Breach Control", effectiveness: "Partially Effective", testResults: "Pending", residualRisk: "[18, Medium]", residualTrend: "↑Increasing", status: "Completed", lastAssessed: "01/22/2026" },
  { riskId: "R-044", title: "Regulatory Breach - Event 44", level: "Level 2", category: "Compliance", owner: "Maria Garcia", assessor: "Risk Team B", inherentRisk: "[56, High]", inherentTrend: "→Stable", controls: "CTRL-045: Regulatory Breach Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[24, Medium]", residualTrend: "→Stable", status: "Completed", lastAssessed: "11/19/2025" },
  { riskId: "R-045", title: "Regulatory Breach - Event 45", level: "Level 1", category: "Compliance", owner: "Emily Chen", assessor: "Internal Audit", inherentRisk: "[56, High]", inherentTrend: "↓Decreasing", controls: "CTRL-046: Regulatory Breach Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[35, Medium]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "01/25/2026" },
  { riskId: "R-046", title: "Regulatory Breach - Event 46", level: "Level 3", category: "Compliance", owner: "Mike Davis", assessor: "Risk Team A", inherentRisk: "[35, Medium]", inherentTrend: "→Stable", controls: "CTRL-047: Regulatory Breach Control", effectiveness: "Ineffective", testResults: "Pass", residualRisk: "[24, Medium]", residualTrend: "↓Decreasing", status: "Sent for Assessment", lastAssessed: "11/15/2025" },
  { riskId: "R-047", title: "Regulatory Breach - Event 47", level: "Level 1", category: "Compliance", owner: "Alex Turner", assessor: "External Auditor", inherentRisk: "[24, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-048: Regulatory Breach Control", effectiveness: "Ineffective", testResults: "Fail", residualRisk: "[35, Medium]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "12/16/2025" },
  { riskId: "R-048", title: "Regulatory Breach - Event 48", level: "Level 1", category: "Compliance", owner: "Maria Garcia", assessor: "Risk Team B", inherentRisk: "[48, High]", inherentTrend: "↓Decreasing", controls: "CTRL-049: Regulatory Breach Control", effectiveness: "Ineffective", testResults: "Pass", residualRisk: "[18, Medium]", residualTrend: "↓Decreasing", status: "Pending Approval", lastAssessed: "01/01/2026" },
  { riskId: "R-049", title: "Regulatory Breach - Event 49", level: "Level 1", category: "Compliance", owner: "David Wilson", assessor: "External Auditor", inherentRisk: "[24, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-050: Regulatory Breach Control", effectiveness: "Partially Effective", testResults: "Fail", residualRisk: "[8, Low]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "12/08/2025" },
  { riskId: "R-050", title: "Policy Violation - Event 50", level: "Level 2", category: "Compliance", owner: "Alex Turner", assessor: "External Auditor", inherentRisk: "[24, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-051: Policy Violation Control", effectiveness: "Design Effective", testResults: "Not Tested", residualRisk: "[8, Low]", residualTrend: "↑Increasing", status: "Completed", lastAssessed: "12/30/2025" },
  { riskId: "R-051", title: "Policy Violation - Event 51", level: "Level 2", category: "Compliance", owner: "Alex Turner", assessor: "External Auditor", inherentRisk: "[24, Medium]", inherentTrend: "→Stable", controls: "CTRL-052: Policy Violation Control", effectiveness: "Ineffective", testResults: "Pending", residualRisk: "[18, Medium]", residualTrend: "↓Decreasing", status: "Pending Approval", lastAssessed: "12/08/2025" },
  { riskId: "R-052", title: "Policy Violation - Event 52", level: "Level 3", category: "Compliance", owner: "Mike Davis", assessor: "Risk Team B", inherentRisk: "[24, Medium]", inherentTrend: "→Stable", controls: "CTRL-053: Policy Violation Control", effectiveness: "Ineffective", testResults: "Pass", residualRisk: "[8, Low]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "01/26/2026" },
  { riskId: "R-053", title: "Policy Violation - Event 53", level: "Level 3", category: "Compliance", owner: "John Smith", assessor: "Risk Team B", inherentRisk: "[48, High]", inherentTrend: "↓Decreasing", controls: "CTRL-054: Policy Violation Control", effectiveness: "Ineffective", testResults: "Not Tested", residualRisk: "[35, Medium]", residualTrend: "↓Decreasing", status: "Sent for Assessment", lastAssessed: "01/03/2026" },
  { riskId: "R-054", title: "Policy Violation - Event 54", level: "Level 3", category: "Compliance", owner: "John Smith", assessor: "Risk Team B", inherentRisk: "[48, High]", inherentTrend: "→Stable", controls: "CTRL-055: Policy Violation Control", effectiveness: "Design Effective", testResults: "Fail", residualRisk: "[24, Medium]", residualTrend: "↑Increasing", status: "Sent for Assessment", lastAssessed: "01/14/2026" },
  { riskId: "R-055", title: "Policy Violation - Event 55", level: "Level 2", category: "Compliance", owner: "Sarah Johnson", assessor: "Compliance Team", inherentRisk: "[24, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-056: Policy Violation Control", effectiveness: "Partially Effective", testResults: "Fail", residualRisk: "[35, Medium]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "12/15/2025" },
  { riskId: "R-056", title: "Policy Violation - Event 56", level: "Level 2", category: "Compliance", owner: "Nina Patel", assessor: "Risk Team B", inherentRisk: "[35, Medium]", inherentTrend: "→Stable", controls: "CTRL-057: Policy Violation Control", effectiveness: "Design Effective", testResults: "Fail", residualRisk: "[35, Medium]", residualTrend: "→Stable", status: "Review & Challenge", lastAssessed: "01/07/2026" },
  { riskId: "R-057", title: "Legal Exposure - Event 57", level: "Level 1", category: "Compliance", owner: "Robert Chen", assessor: "Risk Team A", inherentRisk: "[35, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-058: Legal Exposure Control", effectiveness: "Ineffective", testResults: "Pass", residualRisk: "[8, Low]", residualTrend: "→Stable", status: "Pending Approval", lastAssessed: "12/26/2025" },
  { riskId: "R-058", title: "Legal Exposure - Event 58", level: "Level 1", category: "Compliance", owner: "Maria Garcia", assessor: "Internal Audit", inherentRisk: "[18, Medium]", inherentTrend: "→Stable", controls: "CTRL-059: Legal Exposure Control", effectiveness: "Design Effective", testResults: "Not Tested", residualRisk: "[24, Medium]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "01/13/2026" },
  { riskId: "R-059", title: "Legal Exposure - Event 59", level: "Level 3", category: "Compliance", owner: "Maria Garcia", assessor: "Risk Team B", inherentRisk: "[18, Medium]", inherentTrend: "→Stable", controls: "CTRL-060: Legal Exposure Control", effectiveness: "Partially Effective", testResults: "Pending", residualRisk: "[8, Low]", residualTrend: "→Stable", status: "Pending Approval", lastAssessed: "01/15/2026" },
  { riskId: "R-060", title: "Legal Exposure - Event 60", level: "Level 1", category: "Compliance", owner: "David Wilson", assessor: "Risk Team A", inherentRisk: "[24, Medium]", inherentTrend: "→Stable", controls: "CTRL-061: Legal Exposure Control", effectiveness: "Partially Effective", testResults: "Not Tested", residualRisk: "[8, Low]", residualTrend: "↑Increasing", status: "Sent for Assessment", lastAssessed: "12/21/2025" },
  { riskId: "R-061", title: "Legal Exposure - Event 61", level: "Level 1", category: "Compliance", owner: "Maria Garcia", assessor: "Risk Team B", inherentRisk: "[56, High]", inherentTrend: "↓Decreasing", controls: "CTRL-062: Legal Exposure Control", effectiveness: "Design Effective", testResults: "Fail", residualRisk: "[8, Low]", residualTrend: "↓Decreasing", status: "Pending Approval", lastAssessed: "12/08/2025" },
  { riskId: "R-062", title: "Legal Exposure - Event 62", level: "Level 3", category: "Compliance", owner: "Maria Garcia", assessor: "External Auditor", inherentRisk: "[24, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-063: Legal Exposure Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[8, Low]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "01/19/2026" },
  { riskId: "R-063", title: "Legal Exposure - Event 63", level: "Level 3", category: "Compliance", owner: "Maria Garcia", assessor: "Compliance Team", inherentRisk: "[56, High]", inherentTrend: "↑Increasing", controls: "CTRL-064: Legal Exposure Control", effectiveness: "Design Effective", testResults: "Fail", residualRisk: "[35, Medium]", residualTrend: "↓Decreasing", status: "Pending Approval", lastAssessed: "12/11/2025" },
  { riskId: "R-064", title: "Data Breach - Event 64", level: "Level 2", category: "Technology", owner: "John Smith", assessor: "Risk Team B", inherentRisk: "[18, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-065: Data Breach Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[24, Medium]", residualTrend: "↑Increasing", status: "Sent for Assessment", lastAssessed: "12/08/2025" },
  { riskId: "R-065", title: "Data Breach - Event 65", level: "Level 2", category: "Technology", owner: "Maria Garcia", assessor: "External Auditor", inherentRisk: "[48, High]", inherentTrend: "→Stable", controls: "CTRL-066: Data Breach Control", effectiveness: "Partially Effective", testResults: "Pass", residualRisk: "[8, Low]", residualTrend: "↓Decreasing", status: "Sent for Assessment", lastAssessed: "01/19/2026" },
  { riskId: "R-066", title: "Data Breach - Event 66", level: "Level 1", category: "Technology", owner: "Emily Chen", assessor: "Compliance Team", inherentRisk: "[35, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-067: Data Breach Control", effectiveness: "Design Effective", testResults: "Pending", residualRisk: "[35, Medium]", residualTrend: "↓Decreasing", status: "Pending Approval", lastAssessed: "01/09/2026" },
  { riskId: "R-067", title: "Data Breach - Event 67", level: "Level 3", category: "Technology", owner: "Sarah Johnson", assessor: "External Auditor", inherentRisk: "[18, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-068: Data Breach Control", effectiveness: "Design Effective", testResults: "Pending", residualRisk: "[18, Medium]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "01/13/2026" },
  { riskId: "R-068", title: "Data Breach - Event 68", level: "Level 2", category: "Technology", owner: "Mike Davis", assessor: "Compliance Team", inherentRisk: "[35, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-069: Data Breach Control", effectiveness: "Partially Effective", testResults: "Not Tested", residualRisk: "[18, Medium]", residualTrend: "↑Increasing", status: "Review & Challenge", lastAssessed: "01/25/2026" },
  { riskId: "R-069", title: "Data Breach - Event 69", level: "Level 3", category: "Technology", owner: "David Wilson", assessor: "Compliance Team", inherentRisk: "[35, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-070: Data Breach Control", effectiveness: "Ineffective", testResults: "Not Tested", residualRisk: "[8, Low]", residualTrend: "→Stable", status: "Completed", lastAssessed: "01/27/2026" },
  { riskId: "R-070", title: "Data Breach - Event 70", level: "Level 2", category: "Technology", owner: "Emily Chen", assessor: "Risk Team B", inherentRisk: "[18, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-071: Data Breach Control", effectiveness: "Partially Effective", testResults: "Pending", residualRisk: "[35, Medium]", residualTrend: "↑Increasing", status: "Completed", lastAssessed: "11/20/2025" },
  { riskId: "R-071", title: "Cyber Attack - Event 71", level: "Level 1", category: "Technology", owner: "Alex Turner", assessor: "Compliance Team", inherentRisk: "[48, High]", inherentTrend: "↑Increasing", controls: "CTRL-072: Cyber Attack Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[18, Medium]", residualTrend: "↑Increasing", status: "Completed", lastAssessed: "12/17/2025" },
  { riskId: "R-072", title: "Cyber Attack - Event 72", level: "Level 3", category: "Technology", owner: "Emily Chen", assessor: "Internal Audit", inherentRisk: "[18, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-073: Cyber Attack Control", effectiveness: "Design Effective", testResults: "Not Tested", residualRisk: "[35, Medium]", residualTrend: "→Stable", status: "Completed", lastAssessed: "01/15/2026" },
  { riskId: "R-073", title: "Cyber Attack - Event 73", level: "Level 2", category: "Technology", owner: "Lisa Martinez", assessor: "Risk Team A", inherentRisk: "[24, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-074: Cyber Attack Control", effectiveness: "Partially Effective", testResults: "Fail", residualRisk: "[35, Medium]", residualTrend: "→Stable", status: "Completed", lastAssessed: "12/17/2025" },
  { riskId: "R-074", title: "Cyber Attack - Event 74", level: "Level 1", category: "Technology", owner: "Nina Patel", assessor: "Internal Audit", inherentRisk: "[35, Medium]", inherentTrend: "→Stable", controls: "CTRL-075: Cyber Attack Control", effectiveness: "Partially Effective", testResults: "Not Tested", residualRisk: "[35, Medium]", residualTrend: "↓Decreasing", status: "Pending Approval", lastAssessed: "01/10/2026" },
  { riskId: "R-075", title: "Cyber Attack - Event 75", level: "Level 1", category: "Technology", owner: "Alex Turner", assessor: "Compliance Team", inherentRisk: "[24, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-076: Cyber Attack Control", effectiveness: "Design Effective", testResults: "Fail", residualRisk: "[18, Medium]", residualTrend: "→Stable", status: "Completed", lastAssessed: "12/14/2025" },
  { riskId: "R-076", title: "Cyber Attack - Event 76", level: "Level 3", category: "Technology", owner: "Robert Chen", assessor: "External Auditor", inherentRisk: "[35, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-077: Cyber Attack Control", effectiveness: "Ineffective", testResults: "Not Tested", residualRisk: "[24, Medium]", residualTrend: "→Stable", status: "Pending Approval", lastAssessed: "01/30/2026" },
  { riskId: "R-077", title: "Cyber Attack - Event 77", level: "Level 2", category: "Technology", owner: "David Wilson", assessor: "Risk Team A", inherentRisk: "[18, Medium]", inherentTrend: "→Stable", controls: "CTRL-078: Cyber Attack Control", effectiveness: "Partially Effective", testResults: "Pending", residualRisk: "[8, Low]", residualTrend: "↑Increasing", status: "Sent for Assessment", lastAssessed: "01/22/2026" },
  { riskId: "R-078", title: "System Vulnerability - Event 78", level: "Level 2", category: "Technology", owner: "Emily Chen", assessor: "Compliance Team", inherentRisk: "[18, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-079: System Vulnerability Control", effectiveness: "Partially Effective", testResults: "Fail", residualRisk: "[18, Medium]", residualTrend: "↑Increasing", status: "Completed", lastAssessed: "11/20/2025" },
  { riskId: "R-079", title: "System Vulnerability - Event 79", level: "Level 2", category: "Technology", owner: "Mike Davis", assessor: "External Auditor", inherentRisk: "[56, High]", inherentTrend: "↓Decreasing", controls: "CTRL-080: System Vulnerability Control", effectiveness: "Partially Effective", testResults: "Fail", residualRisk: "[35, Medium]", residualTrend: "→Stable", status: "Review & Challenge", lastAssessed: "01/12/2026" },
  { riskId: "R-080", title: "System Vulnerability - Event 80", level: "Level 3", category: "Technology", owner: "Robert Chen", assessor: "Compliance Team", inherentRisk: "[48, High]", inherentTrend: "→Stable", controls: "CTRL-081: System Vulnerability Control", effectiveness: "Ineffective", testResults: "Pending", residualRisk: "[18, Medium]", residualTrend: "→Stable", status: "Pending Approval", lastAssessed: "01/03/2026" },
  { riskId: "R-081", title: "System Vulnerability - Event 81", level: "Level 1", category: "Technology", owner: "Alex Turner", assessor: "Compliance Team", inherentRisk: "[18, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-082: System Vulnerability Control", effectiveness: "Design Effective", testResults: "Pending", residualRisk: "[18, Medium]", residualTrend: "↑Increasing", status: "Sent for Assessment", lastAssessed: "01/25/2026" },
  { riskId: "R-082", title: "System Vulnerability - Event 82", level: "Level 1", category: "Technology", owner: "Mike Davis", assessor: "Risk Team A", inherentRisk: "[56, High]", inherentTrend: "↓Decreasing", controls: "CTRL-083: System Vulnerability Control", effectiveness: "Ineffective", testResults: "Pass", residualRisk: "[35, Medium]", residualTrend: "↓Decreasing", status: "Completed", lastAssessed: "01/01/2026" },
  { riskId: "R-083", title: "System Vulnerability - Event 83", level: "Level 3", category: "Technology", owner: "Robert Chen", assessor: "Compliance Team", inherentRisk: "[18, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-084: System Vulnerability Control", effectiveness: "Design Effective", testResults: "Not Tested", residualRisk: "[24, Medium]", residualTrend: "↓Decreasing", status: "Sent for Assessment", lastAssessed: "12/08/2025" },
  { riskId: "R-084", title: "System Vulnerability - Event 84", level: "Level 3", category: "Technology", owner: "Emily Chen", assessor: "Compliance Team", inherentRisk: "[18, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-085: System Vulnerability Control", effectiveness: "Partially Effective", testResults: "Fail", residualRisk: "[24, Medium]", residualTrend: "↓Decreasing", status: "Sent for Assessment", lastAssessed: "12/08/2025" },
  { riskId: "R-085", title: "Vendor Failure - Event 85", level: "Level 1", category: "Strategic", owner: "Alex Turner", assessor: "External Auditor", inherentRisk: "[18, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-086: Vendor Failure Control", effectiveness: "Partially Effective", testResults: "Fail", residualRisk: "[35, Medium]", residualTrend: "→Stable", status: "Completed", lastAssessed: "12/08/2025" },
  { riskId: "R-086", title: "Vendor Failure - Event 86", level: "Level 3", category: "Strategic", owner: "David Wilson", assessor: "Risk Team B", inherentRisk: "[56, High]", inherentTrend: "↓Decreasing", controls: "CTRL-087: Vendor Failure Control", effectiveness: "Partially Effective", testResults: "Pending", residualRisk: "[8, Low]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "12/08/2025" },
  { riskId: "R-087", title: "Vendor Failure - Event 87", level: "Level 2", category: "Strategic", owner: "Alex Turner", assessor: "Compliance Team", inherentRisk: "[48, High]", inherentTrend: "↑Increasing", controls: "CTRL-088: Vendor Failure Control", effectiveness: "Design Effective", testResults: "Not Tested", residualRisk: "[35, Medium]", residualTrend: "→Stable", status: "Pending Approval", lastAssessed: "01/17/2026" },
  { riskId: "R-088", title: "Vendor Failure - Event 88", level: "Level 3", category: "Strategic", owner: "David Wilson", assessor: "Compliance Team", inherentRisk: "[35, Medium]", inherentTrend: "→Stable", controls: "CTRL-089: Vendor Failure Control", effectiveness: "Partially Effective", testResults: "Pass", residualRisk: "[35, Medium]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "12/08/2025" },
  { riskId: "R-089", title: "Vendor Failure - Event 89", level: "Level 1", category: "Strategic", owner: "Mike Davis", assessor: "External Auditor", inherentRisk: "[24, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-090: Vendor Failure Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[18, Medium]", residualTrend: "↓Decreasing", status: "Pending Approval", lastAssessed: "01/29/2026" },
  { riskId: "R-090", title: "Vendor Failure - Event 90", level: "Level 3", category: "Strategic", owner: "Robert Chen", assessor: "Compliance Team", inherentRisk: "[18, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-091: Vendor Failure Control", effectiveness: "Partially Effective", testResults: "Not Tested", residualRisk: "[35, Medium]", residualTrend: "→Stable", status: "Completed", lastAssessed: "12/08/2025" },
  { riskId: "R-091", title: "Vendor Failure - Event 91", level: "Level 2", category: "Strategic", owner: "Maria Garcia", assessor: "Compliance Team", inherentRisk: "[35, Medium]", inherentTrend: "→Stable", controls: "CTRL-092: Vendor Failure Control", effectiveness: "Ineffective", testResults: "Fail", residualRisk: "[35, Medium]", residualTrend: "↑Increasing", status: "Review & Challenge", lastAssessed: "01/05/2026" },
  { riskId: "R-092", title: "Market Disruption - Event 92", level: "Level 2", category: "Strategic", owner: "Sarah Johnson", assessor: "Internal Audit", inherentRisk: "[56, High]", inherentTrend: "↓Decreasing", controls: "CTRL-093: Market Disruption Control", effectiveness: "Partially Effective", testResults: "Fail", residualRisk: "[18, Medium]", residualTrend: "↑Increasing", status: "Review & Challenge", lastAssessed: "01/18/2026" },
  { riskId: "R-093", title: "Market Disruption - Event 93", level: "Level 1", category: "Strategic", owner: "Mike Davis", assessor: "Risk Team A", inherentRisk: "[35, Medium]", inherentTrend: "→Stable", controls: "CTRL-094: Market Disruption Control", effectiveness: "Partially Effective", testResults: "Pending", residualRisk: "[8, Low]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "12/08/2025" },
  { riskId: "R-094", title: "Market Disruption - Event 94", level: "Level 3", category: "Strategic", owner: "Emily Chen", assessor: "Risk Team A", inherentRisk: "[18, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-095: Market Disruption Control", effectiveness: "Partially Effective", testResults: "Pass", residualRisk: "[35, Medium]", residualTrend: "↑Increasing", status: "Completed", lastAssessed: "12/24/2025" },
  { riskId: "R-095", title: "Market Disruption - Event 95", level: "Level 2", category: "Strategic", owner: "Sarah Johnson", assessor: "Compliance Team", inherentRisk: "[56, High]", inherentTrend: "↓Decreasing", controls: "CTRL-096: Market Disruption Control", effectiveness: "Ineffective", testResults: "Pass", residualRisk: "[8, Low]", residualTrend: "↑Increasing", status: "Pending Approval", lastAssessed: "01/31/2026" },
  { riskId: "R-096", title: "Market Disruption - Event 96", level: "Level 2", category: "Strategic", owner: "Maria Garcia", assessor: "Risk Team A", inherentRisk: "[48, High]", inherentTrend: "→Stable", controls: "CTRL-097: Market Disruption Control", effectiveness: "Partially Effective", testResults: "Not Tested", residualRisk: "[24, Medium]", residualTrend: "↑Increasing", status: "Sent for Assessment", lastAssessed: "12/08/2025" },
  { riskId: "R-097", title: "Market Disruption - Event 97", level: "Level 2", category: "Strategic", owner: "Emily Chen", assessor: "Compliance Team", inherentRisk: "[48, High]", inherentTrend: "↑Increasing", controls: "CTRL-098: Market Disruption Control", effectiveness: "Design Effective", testResults: "Fail", residualRisk: "[35, Medium]", residualTrend: "→Stable", status: "Pending Approval", lastAssessed: "12/08/2025" },
  { riskId: "R-098", title: "Market Disruption - Event 98", level: "Level 2", category: "Strategic", owner: "Lisa Martinez", assessor: "Internal Audit", inherentRisk: "[48, High]", inherentTrend: "↑Increasing", controls: "CTRL-099: Market Disruption Control", effectiveness: "Ineffective", testResults: "Fail", residualRisk: "[24, Medium]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "12/25/2025" },
  { riskId: "R-099", title: "Reputation Damage - Event 99", level: "Level 1", category: "Strategic", owner: "Robert Chen", assessor: "Internal Audit", inherentRisk: "[35, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-100: Reputation Damage Control", effectiveness: "Partially Effective", testResults: "Pending", residualRisk: "[24, Medium]", residualTrend: "→Stable", status: "Completed", lastAssessed: "12/08/2025" },
  { riskId: "R-100", title: "Reputation Damage - Event 100", level: "Level 3", category: "Strategic", owner: "Nina Patel", assessor: "Internal Audit", inherentRisk: "[56, High]", inherentTrend: "↑Increasing", controls: "CTRL-101: Reputation Damage Control", effectiveness: "Design Effective", testResults: "Pass", residualRisk: "[24, Medium]", residualTrend: "↑Increasing", status: "Sent for Assessment", lastAssessed: "12/08/2025" },
  { riskId: "R-101", title: "Reputation Damage - Event 101", level: "Level 2", category: "Strategic", owner: "Emily Chen", assessor: "Risk Team B", inherentRisk: "[35, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-102: Reputation Damage Control", effectiveness: "Design Effective", testResults: "Not Tested", residualRisk: "[18, Medium]", residualTrend: "→Stable", status: "Pending Approval", lastAssessed: "01/02/2026" },
  { riskId: "R-102", title: "Reputation Damage - Event 102", level: "Level 1", category: "Strategic", owner: "Nina Patel", assessor: "Compliance Team", inherentRisk: "[24, Medium]", inherentTrend: "→Stable", controls: "CTRL-103: Reputation Damage Control", effectiveness: "Partially Effective", testResults: "Pass", residualRisk: "[8, Low]", residualTrend: "↓Decreasing", status: "Completed", lastAssessed: "01/06/2026" },
  { riskId: "R-103", title: "Reputation Damage - Event 103", level: "Level 3", category: "Strategic", owner: "Lisa Martinez", assessor: "Compliance Team", inherentRisk: "[35, Medium]", inherentTrend: "↓Decreasing", controls: "CTRL-104: Reputation Damage Control", effectiveness: "Ineffective", testResults: "Pass", residualRisk: "[24, Medium]", residualTrend: "↑Increasing", status: "Review & Challenge", lastAssessed: "12/27/2025" },
  { riskId: "R-104", title: "Reputation Damage - Event 104", level: "Level 3", category: "Strategic", owner: "Robert Chen", assessor: "Risk Team A", inherentRisk: "[24, Medium]", inherentTrend: "↑Increasing", controls: "CTRL-105: Reputation Damage Control", effectiveness: "Ineffective", testResults: "Not Tested", residualRisk: "[24, Medium]", residualTrend: "↓Decreasing", status: "Review & Challenge", lastAssessed: "12/08/2025" },
  { riskId: "R-105", title: "Reputation Damage - Event 105", level: "Level 1", category: "Strategic", owner: "Robert Chen", assessor: "Risk Team B", inherentRisk: "[56, High]", inherentTrend: "→Stable", controls: "CTRL-106: Reputation Damage Control", effectiveness: "Partially Effective", testResults: "Fail", residualRisk: "[18, Medium]", residualTrend: "↓Decreasing", status: "Pending Approval", lastAssessed: "12/08/2025" },
];

const headers = [
  "Risk ID", "Title", "Level", "Category", "Owner", "Assessor",
  "Inherent Risk", "Inherent Trend", "Controls", "Effectiveness", "Test Results",
  "Residual Risk", "Residual Trend", "Status", "Last Assessed"
];

export async function generateRiskDocx(): Promise<Blob> {
  const headerRow = new TableRow({
    children: headers.map(header => 
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: header, bold: true, size: 18 })] })],
        shading: { fill: "E0E0E0" },
      })
    ),
  });

  const dataRows = riskData.map(risk => 
    new TableRow({
      children: [
        risk.riskId, risk.title, risk.level, risk.category,
        risk.owner, risk.assessor, risk.inherentRisk, risk.inherentTrend,
        risk.controls, risk.effectiveness, risk.testResults, risk.residualRisk,
        risk.residualTrend, risk.status, risk.lastAssessed
      ].map(value => 
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: value, size: 16 })] })],
        })
      ),
    })
  );

  const table = new Table({
    rows: [headerRow, ...dataRows],
    width: { size: 100, type: WidthType.PERCENTAGE },
  });

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({
          text: "Risk Events Data",
          heading: HeadingLevel.HEADING_1,
        }),
        new Paragraph({ text: "" }),
        table,
      ],
    }],
  });

  return await Packer.toBlob(doc);
}

export function downloadRiskDocx() {
  generateRiskDocx().then(blob => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'risk-events-final.docx';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  });
}
